export default function TermsPage() {
  return (
    <div className="min-h-screen bg-navy-base">
      <div className="max-w-[800px] mx-auto px-6 py-16">
        <h1 className="text-32 font-display font-bold text-text-primary mb-8">Terms of Service</h1>
        <div className="prose prose-invert max-w-none text-14 text-text-secondary space-y-6">
          <p><em>Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</em></p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">1. Acceptance of Terms</h2>
          <p>
            By accessing or using VelaBeam, you agree to be bound by these Terms of Service.
            If you do not agree, do not use the service.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">2. Description of Service</h2>
          <p>
            VelaBeam provides tools for discovering local businesses without websites and generating
            industry-specific website content. The service includes lead discovery, AI-powered site
            generation, site management, and deployment features.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">3. User Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials.
            You agree to notify us immediately of any unauthorized use of your account.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">4. Acceptable Use</h2>
          <p>
            You agree not to use VelaBeam for any unlawful purpose, to generate misleading or deceptive
            content, to impersonate businesses without authorization, or to violate any applicable laws
            or regulations.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">5. AI-Generated Content</h2>
          <p>
            Sites generated by VelaBeam using AI are drafts intended for review and customization.
            You are responsible for verifying the accuracy of generated content before publishing
            or presenting it to businesses.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">6. Payment Terms</h2>
          <p>
            Paid plans are billed monthly or annually. All prices are in USD. You may cancel at any time.
            Refunds are handled on a case-by-case basis.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">7. Limitation of Liability</h2>
          <p>
            VelaBeam is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any
            indirect, incidental, or consequential damages arising from your use of the service.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">8. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the service after changes
            constitutes acceptance of the new terms.
          </p>

          <h2 className="text-20 font-semibold text-text-primary font-sans">9. Contact</h2>
          <p>
            For questions about these terms, contact us at legal@velabeam.app.
          </p>
        </div>
      </div>
    </div>
  );
}
